### ISSUE TITLE
Add github-corners to jekyll website header ❤

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#106]
We should use the same as the one here, it looks good 🚀 
https://hacktoberfestchecker.herokuapp.com/

It's https://github.com/tholman/github-corners

![image](https://user-images.githubusercontent.com/1264761/31679193-57e16860-b33e-11e7-8789-941e0952fb61.png)

The orange looks good 🍰

**Comment by AntonyFenton** [comment]
I'll get this for you shortly

**Comment by emileber** [comment]
Sorry, we went a different direction with this.
