### ISSUE TITLE
I fear my ideas will be stolen when sharing them to the group

### ISSUE THREAD

**Issue by emileber** [saglacio/saglac.io-original#114]
Il faudrait aborder ce sujet dans la FAQ.

> J'ai peur de présenter parce que je pense que les gens vont connaitre mes secrets d'entreprise et vont pouvoir jouer dans mes plate-bandes.

La réponse étant que si tu peux te faire voler ton idée et/ou ton créneau en 15 minutes, c'est que ton idée/créneau n'est pas vraiment bon. Anyway, une idée ne vaut rien puisque son succès réside dans la qualité de l'implémentation. 

De plus, l'objectif est de partager des connaissances qui sont normalement disponible à tous.

**Comment by jipiboily** [comment]
1% idea, 99% execution.
