### ISSUE TITLE
Add a success page for the contact form

### ISSUE THREAD

**Issue by emileber** [saglacio/saglac.io-original#117]
> By default, after submitting a form the user is shown the Formspree "Thank You" page. You can provide an alternative URL for that page.
> ```
> <input type="hidden" name="_next" value="//site.io/thanks.html" />
> ```

Il faudrait créer une page (sans lien pour s'y rendre) qui confirme que nous avons bien reçu le message et qu'on y répondra sous peu, avec un lien vers la page d'accueil.

**Comment by jipiboily** [comment]
See #123

**Comment by emileber** [comment]
c'est mergé! 🎉
