### ISSUE TITLE
Invalid certificate on HTTPS

### ISSUE THREAD

**Issue by Ninban** [saglacio/saglac.io-original#122]
Tenter d'aller sur https://saglac.io/ me donne le message suivant :

saglac.io utilise un certificat de sécurité invalide. Le certificat n’est valide que pour les noms suivants : *.github.com, github.com, *.github.io, github.io 
Code d’erreur : SSL_ERROR_BAD_CERT_DOMAIN

**Comment by GabLeRoux** [comment]
@jipiboily une solution est de mettre les dns derrière cloudflare et laisser cloudflare gérer le https. C’est en effet poche mais cette solution fonctionne. Je crois que c’est ce que j’ai finit pr faire avec https://gableroux.com qui est lui aussi sur gh-pages

Related infos: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by jipiboily** [comment]
Sure, j'utilises tjours Cloudflare pour presque tout dans ma vie. Je vais faire ça! :)

**Comment by jipiboily** [comment]
Je viens de faire les switch de nameservers pour aller sur Cloudflare. On doit attendre que ce soit actif. Je check plus tard ce week-end. Une fois confirmé ce sera automatiquement en place...ne me restera que le mise en place de la redirection de saglacio.com vers saglac.io.

**Comment by jipiboily** [comment]
Redirection du .com fonctionnel. Le move a été presque instantanné pour celui là. Le .io est pas encore effectif.

Il va rester à forcer le HTTPS.

**Comment by jipiboily** [comment]
Fixed! And now forces HTTPS, too.
