### ISSUE TITLE
Improve the information on the website

### ISSUE THREAD

**Issue by emileber** [saglacio/saglac.io-original#128]
J'ai demandé du feedback et il va falloir clarifier le site, ce n'est pas au point.

> Vous êtes des développeurs... ? Des informaticiens? Il faut répondre aux Qui ? Quoi, comment, pourquoi? Etc...

> C'est juste des événements ?

> Je pensais que vous étiez un regroupement en premier

> il y a beaucoup de points à lire avant de saisir l'essentiel. Il faudrait en quelques phrases expliquer ce que je dois dire à quelqu'un pour parler de vous. Ensuite, le mettre au début de tous les points mentionnés. Et mettre aussi dans à propos de la page facebook.

Il faudra retravailler, entre autre, la première section du site ainsi qu'ajouter une introduction à la FAQ, et ré-ordonner les sections de celle-ci.

**Comment by GabLeRoux** [comment]
Bon point, je lance ça comme ça (draft):

Le saglac io est un regroupement de passionnés de la technologie, de l’informatique et de l’administration de systèmes. 

Les passionnés sont invité à donner des présentations à des évènements à tous les mois afin de partager des conaissances et résauter autour d’une bière et ou d’un bon repas.

**Comment by emileber** [comment]
Qu'est-ce qu'on met dans ces 6 sections pour décrire le IO?

![image](https://user-images.githubusercontent.com/3286135/31923168-368e84b4-b847-11e7-9a71-3f04fefd3051.png)

**Comment by paaudet** [comment]
Peut-être une section pour mentionner que les gens sont invités peu importe le niveau? Les événements sont vraiment "friendly" et même si, et je parle de mon point de vue, plusieurs sont des cracks et que je ne suis vraiment pas dans votre champ d'expertise, c'est vraiment une ambiance détendu, plaisante et sans prétention. (Ce qui est TRÈS agréable soit dit en passant)

**Comment by emileber** [comment]
Yes, bon point, c'est entre autre ça que je veux transmettre en changeant le

> pour les passionnés du développement logiciel et de l'administration de système

Pour

> pour les passionnés de technologies

Partout.

**Comment by emileber** [comment]
![image](https://user-images.githubusercontent.com/3286135/32260468-7ac947ce-be9e-11e7-8ef3-8813f711b378.png)

**Comment by GabLeRoux** [comment]
* "Un groupe de bénévoles [...]"

Je dirais aussi "le partage des connaissances à coeur", j'ai l'impression que ça se dit mieux.

**Comment by paaudet** [comment]
Peut-être changer l'icône de la loupe par un pinpoint pour l'endroit?

**Comment by emileber** [comment]
@paaudet c'est drôle que tu dise ça parce que c'est déjà l'icône "map-pin", qui est aussi utilisé ailleurs sur le site. 😛 

J'avoue que ça pourrait être confondu avec une loupe, mais l'icône de loupe ne ressemble pas du tout à celui-ci. Voir http://fontawesome.io/icon/search/

**Comment by paaudet** [comment]
@emileber Maintenant que tu le dis, j'avoue que c'est un map-pin, mais oui, j'étais certain que c'était une loupe. Ou le gamer en moi pensait à un joystick d'arcade, lol. ;)

**Comment by emileber** [comment]
#139 est mergé, je ferme ça.
