### ISSUE TITLE
icône .feature-list h3::before devant les titres tombe sur plusieurs lignes sur breakpoint responsive 737px et plus

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#133]
![image](https://user-images.githubusercontent.com/1264761/32004760-8a39f876-b970-11e7-9fd6-453d14108ca0.png)

`@screen and (max-width: 736px)`

![image](https://user-images.githubusercontent.com/1264761/32004969-177c2d6c-b971-11e7-8eb4-41846c27d325.png)

```
.feature-list h3::before {
    position: absolute;
    left: 0;
    top: 0;
    width: 32px;
    height: 32px;
    line-height: 32px;
    font-size: 16px;
}
```

vs `@screen and (min-width: 737px)`:

![image](https://user-images.githubusercontent.com/1264761/32004949-0811a316-b971-11e7-90c2-6e9627037b3c.png)

```
.feature-list h3::before {
    width: 64px;
    height: 64px;
    line-height: 64px;
    margin-right: 0.75em;
    font-size: 32px;
    top: 0.2em;
}
```

L'icône devrait avoir le même comportement que sur mobile car sur tablette, c'est laid avec de long titres ;)

**Comment by emileber** [comment]
Idéalement, il faudrait s'assurer que ça marche bien avec toutes les feature-list, puisque le thème ne faisait que le minimum, soit la feature-list dans la 2e section...

**Comment by chefjuanpi** [comment]
je pense que avec un display table ça doit marcher, alors quand le title besoin plus de un ligne dans n'importe quelle platforme, le texte reste aligne a gauche, du texte sans sauter en bas du icon

**Comment by emileber** [comment]
@chefjuanpi nah pas besoin d'un display table dans ce cas-ci

**Comment by GabLeRoux** [comment]
On a seulement à prendre ce qui fonctionne en mobile et faire la même chose en tablette/screen. D’où le diff que j’ai mis dans l’issue ;)

**Comment by chefjuanpi** [comment]
je le prend en charge, je trouvé déjà la solution

**Comment by emileber** [comment]
Fixed and merged in #137
