### ISSUE TITLE
Hostname "www" missing

### ISSUE THREAD

**Issue by francislr** [saglacio/saglac.io-original#2]
Il manque le bon vieux triple double v
ex.: www.saglac.io

http://no-www.org/faq.php?q=class_C

**Comment by jipiboily** [comment]
En fait je crois que c'est prob de setting DNS...je vais checker plus tard. Merci!

**Comment by francislr** [comment]
Est-ce qu'il faut l'ajouter aussi dans le fichier CNAME ?

**Comment by jipiboily** [comment]
Non, GitHub s'occupe de faire la redirection.

**Comment by jipiboily** [comment]
Ok, j'ai checké vite, erreur de mon côté. Je viens de la corriger mais le TTL était de 3h, je l'ai mis à 15 minutes. On va voir ça ds 3 heures...

**Comment by francislr** [comment]
Ça fonctionne n°1, le TTL peut être remis à une valeur plus élevée
