### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by jipiboily** [saglacio/saglac.io-original#21]
Yeah, already. Not that the current website is not fine, but we are adding a new event: OpenHack. And current website will not work well with more than one event at a time, here is a WIP of the new design, with 3 different menus:
- https://www.dropbox.com/s/xoigebwdf78uxgo/Screenshot%202014-01-21%2021.06.42.png
- https://www.dropbox.com/s/ed44vou0mplubls/Screenshot%202014-01-21%2021.08.39.png
- https://www.dropbox.com/s/sl97otpowqhe5y9/Screenshot%202014-01-21%2021.08.11.png

Let me know your thoughts. Which menu do you prefer?

**Comment by aboudreault** [comment]
The first one is nicer, in my opinion.

**Comment by jipiboily** [comment]
Thanks for the really fast feedback! hehe

**Comment by jipiboily** [comment]
Updated menu for the first one (removed top border radius after feedback from @belug23): https://www.dropbox.com/s/77x2g6o7b0nrsgp/Screenshot%202014-01-22%2016.15.23.png

**Comment by belug23** [comment]
Ah! That's better!

First one still my choice, but the third could be ok too!

**Comment by jpsirois** [comment]
The first is better, but I would make the font bigger. And also I really not sure I’m a big fan of the font for the title, IMO.

Trying different font-weight and changing the letter-spacing, is often a quick-win in big text. Here couple of interesting free font with lot of font-weight to play with :
- [Source Sans Pro](http://www.google.com/fonts/specimen/Source+Sans+Pro)
- [Aleo](http://fontfabric.com/aleo-free-font/) Has less font-weight but still really nice
- [Merriweather Sans](http://www.google.com/fonts/specimen/Merriweather%20Sans)
- [Open Sans](http://www.google.com/fonts/specimen/Open+Sans)

A nice font for title I think is Trebuchet MS which is built-in in every system!

Also if you want a fast way to experiment with Web Font you should take a look at this Bookmarklet: http://somadesign.ca/projects/fontfriend/

And finally a quick list of some of the best Google Web Font Familly is nicely listed here: http://somadesign.ca/demos/better-google-fonts/

**Comment by jipiboily** [comment]
Awesome. Loving the bookmarklet! Thanks for all the feedback in the PR and over IM, too! :)

Working on improvements, I hope to have a part of the work to be done soon-ish.

**Comment by jipiboily** [comment]
Closing this in favor of the PR #22.

Thanks guys! Feel free to contribue!
