### ISSUE TITLE
Le bouton responsive pour le menu déroulant de foundation ne fonctionne pas toujours sur iphone

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#27]
Tout est dans le titre ;).

Je ne sais pas si c'est un bug seulement de mon côté, mais parfois, le bouton du menu déroulant de foundation ne fait rien. Seulement testé avec mon iPhone sous ios7 avec safari.

Pour reproduire le bug:
aller sur [saglac.io](http://www.saglac.io) avec un iphone et cliquer sur le bouton du menu.
 ![saglacbutton](https://f.cloud.github.com/assets/1264761/2127890/e4098fce-9273-11e3-94a1-3a533c0e91e7.png)
Si ça fonctionne, passer à la page `À propos` à l'aide du menu et essayer de cliquer à nouveau sur le le bouton.

Après avoir testé un peu, je crois que le bouton du menu devrait avoir un href

```
 <a class="left-off-canvas-toggle menu-icon" href="#">
    <span>io</span>
 </a>
```

Je vient de tester sous iOS 6.1 Simulator (ios7) avec l'inspecteur de safari et quand j'ajoute un href, le bouton fonctionne à nouveau. Je refais quelques testes cette après-midi et je t'envoie un pr ;)

![capture d ecran 2014-02-10 12 49 16](https://f.cloud.github.com/assets/1264761/2128513/c0bd7cd0-927b-11e3-91c0-3607840015e8.png)
![capture d ecran 2014-02-10 12 49 33](https://f.cloud.github.com/assets/1264761/2128511/c0859e00-927b-11e3-9ecf-502bd4c55da1.png)
![capture d ecran 2014-02-10 12 49 42](https://f.cloud.github.com/assets/1264761/2128512/c0859c70-927b-11e3-9f73-b98f59c1bfaa.png)

**Comment by jipiboily** [comment]
Merci! :)
