### ISSUE TITLE
New website?

### ISSUE THREAD

**Issue by jipiboily** [saglacio/saglac.io-original#3]
Taking notes for what could be part of the new website.
## Features

:white_small_square: New desgin + logo?
:white_small_square: Responsive
### Sections

:white_small_square: Events
:white_small_square: Blog / Anouncement? (including RSS)
:white_small_square: Replacement for Google Group (Discourse?)
:white_small_square: Links:
- :white_small_square: http://gatos02.com/

**Comment by francislr** [comment]
Il serait cool d'utiliser jekyll, ça nous permettrait de laisser le site sur Pages
Mon point de vue sur le design :
- Flat
- Thin font
- Fluid
- Logo simple

Contenu :
- Présentation de l'événement & idée
- Événements à venir (endroits, speakers) avec bouton inscription en évidence
- Événements passés et lien vers les présentations
- Lien vers Google Groups
- Footer (crédits & links)

Le tout serait probablement mieux dans une seule page.
Je crois qu'il serait envisageable d'utiliser Discourse seulement dans le cas où le Google Groups devient très actif. J'ai lu qu'il est en bêta, c'est une idée intéressante.

Je vais faire un croquis rapide bientôt...

**Comment by jipiboily** [comment]
Ça pourrait être autre chose en Ruby aussi, j'ai un VPS sur lequel je pourrais facilement ajouter héberger un site, fait par exemple avec Middleman.

Si toute fois quelqu'un commençait quelque chose, me faire signe, juste pour ne pas dédoubler le travail (je ne sais pas quand j'aurai du temps).

Aussi, si quelqu'un y travail, je suggère de pousser souvent des mises à jour dans un PR, question de voir l'évolution et avoir du feedback rapide pour ne pas que personne ne travail inutilement...;)

Pour Discourse: je suis d'accord.

**Comment by GabLeRoux** [comment]
J'ai fait un truc en fin de semaine (c'était plutôt pour essayer jekyll et compass), et j'ai quelque chose d'intéressant. Je vais faire un pull request quand j'aurai un peu de temps demain. En gros, j'ai créé un theme responsive a l'aide de compass/sass, j'ai un gruntfile qui s'occupe de recompiler et faire le webserver et faire le livereload sur le browser.

Je n'ai pas donné de nouvelles ni fait de pr encore car au début, j'étais vraiement pas convaincu de mon travail, mais cmest de plus en plus ok :P.

J'étais rendu à faire un feed.xml et les evenements sont pour le moment des post avec quelques variables. Ça fonctionne plutôt bien, mais je n'ai pas encore regardé comment fonctionne le déploiement de jekyll sur gh donc mon pr ne sera peut être pas parfait ;)

Comme les calendriers peuvent effectuer des abonnements, je vais regarder comment on fait un feed de calendrier après mon pr demain pm.

**Comment by jipiboily** [comment]
Screenshot &/|| video welcomed :)

Pas besoin d'être parfait. Au contraire. Commit early, commit often. "Deliver" early, deliver often...ça permet d'avoir du feedback avant d'être trop avancé dans une direction qui des fois n'est pas 100% la bonne (je parle en général ici).

**Comment by GabLeRoux** [comment]
Je crois que j'vais prendre un petit break de physique, je balance ça à l'instant ;)

**Comment by francislr** [comment]
Cool! J'ai hate de voir vers quelle direction le design penche...

**Comment by GabLeRoux** [comment]
[gh-pages sur mon fork](http://gableroux.github.io/saglac.io/) (wip: j'attend après les build de gh-pages et j'avais oublié de spécifier baseurl: /saglac.io dans le jekyll config)

[mon fork](https://github.com/gableroux/saglac.io)

J'ai surtout fait une tentative d'utilisation de jekyll, compass, sass et grunt plutôt qu'un design, mais avec ce qu'il y a en ce moment, c'est sensé être super facile de faire un beau design, il ne me reste qu'à voir comment les grilles fonctionnent dans compass.

Je suis en train d'essayer d'envoyer le tout sur sur mon fork, mais gh-pages n'a pas chargé mon site car je ne m'étais pas rendu compte que le fichier CNAME avait un impact aussi important ;)

Comme c'est un peu long, voici quelques screenshots en attendant. Vous remarquerez que c'est pas très stylisé (du moins, moi je trouve qu'il manque encore quelque chose), mais je me suis plutôt concentré à apprendre jekyll et autre.

![capture decran 2013-11-04 a 22 12 56](https://f.cloud.github.com/assets/1264761/1470906/048dd83e-45cd-11e3-9765-5eac84c8e0f0.png)
![capture decran 2013-11-04 a 22 13 06](https://f.cloud.github.com/assets/1264761/1470907/048e292e-45cd-11e3-8feb-3464a59a952b.png)
![capture decran 2013-11-04 a 22 13 08](https://f.cloud.github.com/assets/1264761/1470908/04901676-45cd-11e3-81e5-6370580e291a.png)

J'ai aussi tenté de travailler avec du [vertical rythm](http://webdesign.tutsplus.com/articles/design-theory/improving-layout-with-vertical-rhythm/), il y a moyen de faire afficher la grille, un petit bout de code à décommenter dans le scss. ;)

![capture decran 2013-11-04 a 22 13 36](https://f.cloud.github.com/assets/1264761/1470909/0490a1e0-45cd-11e3-9366-670d520040f8.png)

ps: les sections manquent encore d'espace et il reste beaucoup de travail à faire dans le scss :P

**Comment by jipiboily** [comment]
@GabLeRoux j'ai pas regardé le code encore, en gros, utilises-tu un framework quelconque comme Boostrap ou autre ou c'est codé majoritairement à la main?

PS: le repo de Jekyll a été déplacé il moins d'une heure ici: https://github.com/jekyll/jekyll

**Comment by jipiboily** [comment]
Si ce n'est pas le cas, je suggère d'utiliser un de ces frameworks: Bootstrap, Foundation ou Skeleton. Dans un premier temps finalement je ferais ça assez short and sweet:
- événements passés avec le lien vers les slides et le code s'il y a lieu.
  -- ajouter les avatar Twitter des speakers
- lien vers le Google Group
- lien vers le compte Twitter: https://twitter.com/saglacio
- formulaire d'abonnement à la mailing list
- détails sur la formule
- courriel en évidence pour proposer des talks.

**Comment by GabLeRoux** [comment]
Pour le moment, J'utilise compass avec blueprint sans librairie en particulier, mais les colonnes sont gérés par blueprint. C'est en sass donc cmest assez flexible. Je termine ma session la semaine prochaine donc je boss sur ça dès que j'ai terminé.

Perso je n'aime pas beaucoup bootstrap parce que ça surcharge le html de classes et de div inutiles, il est surutilisé et on le voit partout.

Je vais regarder pour utiliser quelque chose comme foundation ou pure au besoin.

Concernant jekyll, le système d'events est plutôt un hack, mais il est facile à gérer donc de ce côté c'est ok.

Je vais rejouer avec tout ça bientôt et je vais respecter la checklist que tu viens de proposer ;)

Cordialement,
Gabriel Le Breton

**Comment by jipiboily** [comment]
Je peux comprendre pour l'aspect moins sémantique de Bootstrap. Ceci dit, écrire qqchose from scratch me fait moins trippé un peu...mais bon, pas 100% contre!

Encore pour Bootstrap, je pensais à qqchose avec un thème et surtout sans le menu du haut traditionnel qu'on voit partout.

Je ne suis pas un fan de blueprint. Ça fait, mais ça date deux ans et demi, je doute que ce soit future-proof...;)

Ça pourrait aussi être fait avec Middleman, ou même une application Rails...je pourrais l'héberger sur mon serveur, et on pourrait faire une BD pour les événements...ce serait vraiment hyper simple! Est-ce que ça sonne overkill?

/cc @belug23 @dmorissette @aboudreault @juliensam @pmrenaud

**Comment by aboudreault** [comment]
J'ai le même avis que toi concernant blueprint. À mon avis, bootstrap 3 est simplement un must. Ce que nous avons besoin est très simple et une combinaison de Jekyll + Bootstrap3 serait parfait. Il y a une multitude de theme minimaliste qui nous permetterais d'avoir un beau style de base. 

Concernant rails, je doutes qu'on nous voulions commencer à gérer les events, incriptions etc.... donc une simple page jekyll par events pourrait faire l'affaire.

my 2 cents! :)

**Comment by jipiboily** [comment]
Pour l'app Rails, en fait, c'était juste une table avec:
- date événement
- quels sont les talks
- les speakers
- lien pour chaque talk

That's it. Pas d'inscription ou rien...juste pas trop de copier-coller...mais p-e inutile pour le moment...:)

**Comment by GabLeRoux** [comment]
RegardeZ comment je l'avais imaginé avec jekyll:

https://raw.github.com/GabLeRoux/saglac.io/master/_posts/2013-10-29-IO-beta-1.markdown

Avec ce que j'ai, pour ajouter un event, y suffit de créer un markdown comme ça. Très simple et on peut ajouter du style à un bouton eventbrite par le template. C'est très minimaliste et ça fonctionne déjà. Je vais arranger quelques trucs et faire une demande de pr après avoir changer blueprint pour un autre truc.

Cordialement,
Gabriel Le Breton

**Comment by jipiboily** [comment]
super, et on partira de là :)

Merci!

**Comment by jipiboily** [comment]
J'ai mis un nouveau site en ligne, qu'en dites-vous? Je vais envoyer un courriel demain. Tout feedback serait apprécié entre temps! :)

**Comment by aboudreault** [comment]
Je trouve ca parfait! Merci!!

**Comment by jipiboily** [comment]
Closing. Feel free to open new PRs for new features you might want! :)
