### ISSUE TITLE
Add slides into the design, somewhere

### ISSUE THREAD

**Issue by jipiboily** [saglacio/saglac.io-original#33]
Includes:
- [x] add icon for slides
- [ ] add icon for other links (repo or something else)
- [ ] add all previous slides that we can find
- [ ] do not crash or be awful if there is no slides
- [ ] have enough space for at least slides + one link, ideally a couple links would not break all the things!

**Comment by GabLeRoux** [comment]
Repository icon: 
http://iconmonstr.com/cloud-19-icon/
http://iconmonstr.com/cloud-28-icon/

Slides icon
http://iconmonstr.com/sitemap-4-icon/
http://iconmonstr.com/tv-16-icon/

Ma présentation sur meteor
http://meteor.gableroux.com/

J'ai pas le temps des ajouter en pull request, on a le game jam demain à l'UQAC et j'ai un tas de trucs à préparer ;)

**Comment by jipiboily** [comment]
Super, c'est déjà un début. La première personne qui a le temps (toi, moi ou qqun d'autre) c'est ben correct, no rush :)

**Comment by jipiboily** [comment]
Slides pour le talk de @aboudreault sur Pyramid: https://dl.dropboxusercontent.com/u/6210261/introduction-pyramid.zip

**Comment by francislr** [comment]
Good, ça va me faire un bon gabarit pour ma présentation :)

**Comment by aboudreault** [comment]
@francislr jette un coup d'oeil à hovercraft si tu veux le même gabarit: https://hovercraft.readthedocs.org/en/1.0/

**Comment by GabLeRoux** [comment]
Closing issue in favor of #72 :)
