### ISSUE TITLE
Add animate.css

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#36]
Ça, c'est badass et ça nous le prend: http://daneden.github.io/animate.css/
https://developers.facebook.com/tools/debug/

Et il faudrait gérer les tags open graph. et mettre une image de partage (og:image)

![io-facebook-default](https://f.cloud.github.com/assets/1264761/2353207/bbfd7636-a59b-11e3-8a8c-9f17cb94c083.png)

Ça pourrait être cool ^^.

**Comment by jipiboily** [comment]
Bonne idée pour les tags open graph, et aussi [Twitter card](https://dev.twitter.com/docs/cards)!

Pour l'animate, p-e. J'aimerais voir l'effet que tu imagines et le logo et tout...pas 100% convaincu encore mais très possible que je sois convaincu en voyant le résultat :)

Merci pour les suggestions!

**Comment by jipiboily** [comment]
J'ai créé des issues pour FB et Twitter.

Pour l'animation, tu me laisseras savoir si tu as envoie de t'y attaquer. Je suppose que la première étape est d'avoir un logo et images et tout first?

**Comment by jipiboily** [comment]
Closing. It's been over 3 years. Reopen if appropriate.
