### ISSUE TITLE
jquery loaded using http instead of https pa pa paaaan

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#75]
https://github.com/saglacio/saglac.io/blob/gh-pages/_layouts/default.html#L18

We should load remote assets using the magic `//` so we let the browser determine the right protocol . Paul Irish to the rescue https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by emileber** [comment]
on va tout régler ça dans l'issue #77

**Comment by emileber** [comment]
En fait, le https ne fonctionne pas sur github pages lorsqu'un domaine custom est configuré.

**Comment by GabLeRoux** [comment]
Je recommande quand même d'utiliser le relative protocol url comme dans la description. C'est pas que https ne fonctionne pas, c'est qu'il n'est pas enforcé. On pourrait ajouter un redirect en js, mais c'est pas super cool.

Bref, when in doubt, use `<link href="//example.com/some/style.css" rel="stylesheet" type="text/css" />` 🚀

**Comment by GabLeRoux** [comment]
Je ferme l'issue, dans le nouveau design, on a une seule lib externe et on utilise déjà cette technique 👍 
https://github.com/saglacio/saglac.io/blob/1490b89/_layouts/default.html#L23
