### ISSUE TITLE
Use rouge instead of pygments (github-pages warning)

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#76]
We're getting the following email on each page build, let's fix this.

The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by emileber** [comment]
This is fixed I think: `highlighter:  rouge`?

**Comment by GabLeRoux** [comment]
yup
