### ISSUE TITLE
Branding and new website theme

### ISSUE THREAD

**Issue by emileber** [saglacio/saglac.io-original#77]
Ici, nous allons discuter du nouveau theme que je désire appliquer au site.

Idéalement, il doit

- fonctionner facilement avec Jekyll, donc tout ce qui est static va s'utiliser facilement.
- offrir une page de blog
- avoir une page d'accueil style promo d'événement/produit
- être responsive (duh!)

On a parlé de [ThemeForest](https://themeforest.net/) ($$) et j'avais vu [Jekyll Themes](http://jekyllthemes.org/) (gratuit, mais moins beau).  
**Edit:** et https://wrapbootstrap.com/

Une fois choisi, je vais appliquer le theme au site actuel sur une feature branch et je vais intégrer le nouveau logo, de nouvelles images (qu'on devra prendre dans les IO) ainsi que les vieilles données.

Il faudra s'assurer que le nouveau site:

- [ ] Est bien référencé
- [ ] Se partage bien sur les réseaux sociaux (open graph)
- [ ] Intègre les twitter cards
- [ ] Explique bien l'événement
- [ ] Indique clairement comment nous rejoindre
- [ ] Offre une section de partenaires (logo)

**Comment by jipiboily** [comment]
À open graph, j'ajouterais les Twitter Cards (super easy).

Pour le thème ça peut aussi être sur https://wrapbootstrap.com/

**Comment by jlap** [comment]
>  Offre une section de partenaires (logo)
 
Il faudrait établir une procédure pour ça.

Ex. sur le site de mapserver, pour faire partie de: http://mapserver.org/community/service_providers.html il y a une spec ici: http://mapserver.org/development/rfc/ms-rfc-116.html#rfc116

Ce n'est pas le même use case, mais le besoin est semblable, il faut définir comment une compagnie tombe dans les partenaires, et comment elle y reste.

**Comment by emileber** [comment]
@jlap J'aime bien l'idée que pour être un "Core Contributors", l'entreprise doit employer des "committers". On pourrait offrir le même genre de truc puisqu'on ne cherche pas vraiment à ramasser de l'argent.

Par exemple, pour être un **Partenaire**, l'entreprise doit fournir X présentations approuvées par année. Sinon, elle ne peut être admissible qu'à la catégorie **Contributeur**.

On pourra élaborer d'autres conditions ou opportunités, comme par exemple prêter de l'équipements, une salle etc pourrait suffir à se qualifier.

**Comment by emileber** [comment]
Peut-être aussi une page *Awesome products with free plans* qui rassemblerait toutes nos trouvailles.

**Comment by emileber** [comment]
@jlap est-ce que tu peux ajouter les fichiers sources pour le logo? Peut-être nous faire des exports en PNG quand t'auras le temps (Je n'ai pas Photoshop/Illustrator/autres).

**Comment by emileber** [comment]
Discussion pour le choix de theme dans #78

**Comment by jlap** [comment]
![logo_large](https://cloud.githubusercontent.com/assets/4561544/22532086/112eaabe-e8b3-11e6-99e2-e41fdb615587.png)


[logo.zip](https://github.com/saglacio/saglac.io/files/746512/logo.zip)

Voilà un zip avec une couple de formats / grandeurs. Le font est [code pro light](http://www.myfonts.com/fonts/font-fabric/code-pro/) mais le .psd dans le zip a les path pas besoin du fichier. J'ai essayé de faire un favicon pas trop laite mais ça sortait mal lol.

**Comment by jipiboily** [comment]
Closing, it's in prod.
