### ISSUE TITLE
Choose a theme for the new website

### ISSUE THREAD

**Issue by emileber** [saglacio/saglac.io-original#78]
Je propose les themes suivants:

- https://wrapbootstrap.com/theme/rinjani-multi-purpose-one-page-theme-WB035T192
- https://wrapbootstrap.com/theme/stamp-responsive-startup-theme-WB0M409X7

Voir cette page: https://wrapbootstrap.com/themes/landing-pages/page.1/sort.sales/order.desc

J'hais pas les video background bien qu'on ait pas de vidéo encore.

**Comment by GabLeRoux** [comment]
Je recommande de ne pas utiliser de thème payant; le site est open source et donc exposera le thème payé publiquement. Je doute que ce soit legit à moins qu'on me démontre le contraire dans les user agreements de wrapbootstrap (j'ai pas vérifié) :scream:

En solution alternative, on peut facilement utiliser un thème bootstrap free et le personaliser un peu:
http://bootswatch.com

J'ai fait ça pour mon site https://gableroux.com et ça foncionne plutôt bien, j'ai seulement un petit glitch sur mobile avec le footer, j'ai ça dans ma todo :P

**Comment by GabLeRoux** [comment]
En solution alternative, on peut facilement utiliser un thème bootstrap free et le personaliser un peu:
http://bootswatch.com

J'ai fait ça pour mon dite https://gableroux.com et ça foncionne plutôt bien, j'ai seulement un petit glitch sur mobile avec le footer, j'ai ça dans ma todo :P

**Comment by orditeck** [comment]
HTML5 Up font de bons thèmes gratuits! https://html5up.net/

Ils en ont aussi des tout prêt pour Jekyll
http://arkadianriver.github.io/spectral/
https://html5up.net/twenty
https://andrewbanchich.gitlab.io/forty-jekyll-theme/

J'ai testé avec https://github.com/jekyll/jekyll-admin pour le fun afin de voir comment on peut gérer les posts/pages via une admin et c'est assez cool.

**Comment by emileber** [comment]
d'autres thèmes gratuis: https://startbootstrap.com/

**Comment by emileber** [comment]
Les licences sont effectivement assez restrictives: http://support.wrapbootstrap.com/knowledge_base/topics/usage-licenses

**Comment by emileber** [comment]
J'aime bien lui dans HTMLup: https://html5up.net/escape-velocity

@orditeck, ils ont l'air d'utiliser leur lib CSS maison?

**Comment by orditeck** [comment]
@emileber en effet, j'avais pas regardé. C'est dommage.

**Comment by emileber** [comment]
J'ai lu qu'ils utilisaient le framework CSS lightweight [Skel](https://github.com/ajlkn/skel). Ça pourrait faire la job.

**Comment by jipiboily** [comment]
Hey, je viens de me rendre compte que le site n'a pas changé de look...par pure curiosité, est-ce que quelqu'un est sur le cas ou pas vraiment?

**Comment by emileber** [comment]
J'ai été un peu occupé dernièrement, mais j'ai downloadé le thème et j'ai commencé à regarder.

**Comment by jipiboily** [comment]
No stress, j’étais sur le repo et j’étais surtout curieux :)


JP Boily

Founder @ Metrics Watch - Email Reports & Real-time Alerts for Google Analytics

PS: can you trust your Google Analytics data❓ Chances are, probably not. We built a free tool, the Metrics Doctor, to analyze your Google Analytics account and help you make it trustworthy and useful.

PPS: Want to get the most out of Google Analytics? Get our free email course.

**Comment by emileber** [comment]
Mon objectif est de le faire en octobre et ainsi recevoir mon t-shirt [Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 😛

**Comment by GabLeRoux** [comment]
Je ferai les reviews et je pourrai te donner un coup de main avec plaisir ;)

**Comment by emileber** [comment]
C'est starté dans la branche `feature/new-template`.

J'en ai profité pour mettre à jour Jekyll et pouvoir utiliser sass automatiquement.
